ministryofjustice/opg-digi-deps-client

app/Resources/views/moj_template.html.twig, src/AppBundle/Resources/assets/scss/application-ie8.scss, src/AppBundle/Resources/assets/scss/application.scss, src/AppBundle/Resources/assets/scss/components/_account-closing-balance-form.scss, src/AppBundle/Resources/assets/scss/components/_forms.scss
Didn't have to do much for IE, pretty much works.
=> Dd 680 ie support

src/AppBundle/Resources/views/Index/terms.html.twig
=> added personal information charter text to the t&c page

src/AppBundle/Entity/Account.php, src/AppBundle/Entity/AccountTransaction.php, src/AppBundle/Entity/Asset.php, src/AppBundle/Resources/translations/validators.en.yml, tests/behat/features/05-report.feature
- asset valu
- account closing/opene balance
- transaction amount
behat test
=> dd-861 form validation for integer values (Avoid app error on big values)

src/AppBundle/Resources/assets/scss/components/_nav-tabs.scss, src/AppBundle/Resources/assets/scss/components/_report-list.scss, src/AppBundle/Resources/views/Asset/_no_asset_form.html.twig, src/AppBundle/Resources/views/Asset/assets.html.twig, src/AppBundle/Resources/views/Contact/index.html.twig, src/AppBundle/Resources/views/Decision/decisions.html.twig, tests/behat/features/12-report-explanations.feature
@ztolley  let me know if you are happy with the CSS changes
=> Dd 858 swap decision, contacts, 

src/AppBundle/Resources/translations/report-account.en.yml
=> simplify save button

src/AppBundle/Resources/translations/validators.en.yml
changed firstname to first name and lastname to last name
=> content changes

src/AppBundle/Resources/translations/email-password-change.en.yml, src/AppBundle/Resources/translations/email-password-forgotten.en.yml, src/AppBundle/Resources/translations/email.en.yml, src/AppBundle/Resources/views/Email/password-forgotten.text.twig, src/AppBundle/Resources/views/Email/report-submission.html.twig
- amend content for password change email (html)
- amend subject lines and fromNames for all emails
- amend content for password forgotten email (text and html)
- amend content for report submission email
=> email_updates

src/AppBundle/Resources/views/Asset/_listAsset.html.twig, src/AppBundle/Resources/views/Decision/_listDecision.html.twig, src/AppBundle/Tests/Service/ApiClientTest.php, src/AppBundle/Tests/Twig/ComponentsExtensionTest.php, src/AppBundle/Twig/ComponentsExtension.php, tests/behat/features/16-reset-password.feature
=> Behat links and region now using unit-tested twig filter to make-names-like-this-and-strip-out-special-chars

src/AppBundle/Controller/UserController.php, tests/behat/bootstrap/DebugTrait.php, tests/behat/bootstrap/EmailTrait.php, tests/behat/features/02-set-password.feature
-  fix my-details for admin showing full form
-  user activate cross-area check 	
-  behat debugTrait add URL and response code
=> Dd 899 admin fixes

src/AppBundle/Resources/translations/authentication.en.yml, src/AppBundle/Resources/translations/login.en.yml
Fix small typo in inactivity messages - missing ‘due’
=> fix-inactivity-message

src/AppBundle/Resources/translations/report-account.en.yml, src/AppBundle/Resources/views/Account/account.html.twig
This is only for the transactions page in response to current user issues
=> Warn user if leaving transactions page without saving

src/AppBundle/Resources/translations/accounts.en.yml, src/AppBundle/Resources/translations/client.en.yml, src/AppBundle/Resources/translations/report-account.en.yml, src/AppBundle/Resources/translations/report-accounts.en.yml, src/AppBundle/Resources/translations/report-contacts.en.yml, src/AppBundle/Resources/translations/report-overview.en.yml, src/AppBundle/Resources/translations/validators.en.yml, src/AppBundle/Resources/views/Account/_accountTransaction.html.twig
Update content to be in the OPG house style:
* Amend error message for Is the start date of your reporting period and the opening balance date the same? from Please select an option to Choose Yes or No
* Remove extra space in Is the start date of your reporting period and the opening balance date the same ?
* Change Enter the last 4 numbers of the account number to Enter the last four numbers of the account number
* On Accounts page, remove Total Value label by description box
* Change Transfers out to other client’s accounts to Transfers out to client’s other accounts
* Change Bank or Building Society to Bank or building society
* Change Total Balance to Total balance
* Change Country (Optional) to Country (optional)
* Fix typo ‘You can only sign off the accounts’ section at the end of …
=> Content 02 09 15

src/AppBundle/Resources/translations/activation-link-sent.en.yml, src/AppBundle/Resources/translations/authentication.en.yml, src/AppBundle/Resources/translations/client.en.yml, src/AppBundle/Resources/translations/feedback.en.yml, src/AppBundle/Resources/translations/login.en.yml, src/AppBundle/Resources/translations/password-forgotten.en.yml, src/AppBundle/Resources/translations/password-reset-expired.en.yml, src/AppBundle/Resources/translations/password-reset.en.yml, src/AppBundle/Resources/translations/password-sent.en.yml, src/AppBundle/Resources/translations/report-account.en.yml, src/AppBundle/Resources/translations/report-accounts.en.yml, src/AppBundle/Resources/translations/report-assets.en.yml, src/AppBundle/Resources/translations/report-contacts.en.yml, src/AppBundle/Resources/translations/report-decisions.en.yml, src/AppBundle/Resources/translations/report-declaration.en.yml, src/AppBundle/Resources/translations/report-further-information.en.yml, src/AppBundle/Resources/translations/report-overview.en.yml, src/AppBundle/Resources/translations/report-safeguarding.en.yml, src/AppBundle/Resources/translations/report-submitted.en.yml, src/AppBundle/Resources/translations/user-activate-expired.en.yml, src/AppBundle/Resources/translations/user-activate.en.yml, src/AppBundle/Resources/translations/user-details.en.yml
Amend page titles for consistency/house style
Remove lorem text and replace with “ “
=> content-03-09-15

src/AppBundle/Resources/translations/registration.en.yml, src/AppBundle/Resources/translations/report-contacts.en.yml, src/AppBundle/Resources/translations/validators.en.yml, src/AppBundle/Resources/views/Decision/_decision_form.html.twig
Update page titles for consistency
Amend error message - should be types of court order, not types of
deputy
Remove reference to taking out loans from bullet list of examples of
different types of significant decisions
Amend description to include reference to decision making
=> Content 09 09 15

src/AppBundle/Resources/translations/report-submitted.en.yml, src/AppBundle/Resources/views/Decision/_decision_form.html.twig, src/AppBundle/Resources/views/Report/submitConfirmation.html.twig
Update content on Report submitted page.
=> content-report-submitted-text

README.md, src/AppBundle/Resources/views/Index/terms.html.twig, src/AppBundle/Resources/views/Layouts/application.html.twig
Amend ‘Complete the Deputy Report’ or ‘Complete the Deputy report’ to
‘Complete the deputy report’ (incorrect capitalisation)
=> content-update-service-title

src/AppBundle/Resources/translations/validators.en.yml
Update error messages in OPG house style
=> Content 15 09 15

src/AppBundle/Resources/translations/report-assets.en.yml, src/AppBundle/Resources/translations/report-safeguarding.en.yml, tests/behat/features/deputy/11-safeguarding/03-userreport.feature
Amend Other assets to Other valuable assets in Assets section
Include example of unpaid care in Safeguarding section
Amend Everyday to Every day in Safeguarding section
=> content-25-09-15

src/AppBundle/Resources/translations/authentication.en.yml, src/AppBundle/Resources/translations/error.en.yml, src/AppBundle/Resources/translations/login.en.yml
Update title of 404 page in line with gov.uk 
Amend link text - Create an account or sign in
Amend Complete a deputy report to Complete the deputy report
(consistent with name of service)
=> Content 06 10 15

src/AppBundle/Controller/UserController.php, src/AppBundle/Form/AssetType.php, src/AppBundle/Resources/assets/javascripts/date.js, src/AppBundle/Resources/translations/login.en.yml, src/AppBundle/Resources/translations/report-account-balance.en.yml, src/AppBundle/Resources/translations/report-accounts.en.yml, src/AppBundle/Resources/translations/report-assets.en.yml, src/AppBundle/Resources/translations/validators.en.yml
Small house style amends - see individual commits for details.
=> Content 30 10 15

src/AppBundle/Controller/AssetController.php, src/AppBundle/Form/SafeguardingType.php, src/AppBundle/Resources/translations/home.en.yml, src/AppBundle/Resources/translations/report-assets.en.yml, src/AppBundle/Resources/translations/report-contacts.en.yml, src/AppBundle/Resources/translations/report-decisions.en.yml, src/AppBundle/Resources/translations/report-safeguarding.en.yml, src/AppBundle/Resources/views/Asset/_asset_edit_form.html.twig, src/AppBundle/Resources/views/Asset/_noAssets.html.twig, src/AppBundle/Resources/views/Asset/addComplete.html.twig, src/AppBundle/Resources/views/Asset/addSelectTitle.html.twig, src/AppBundle/Resources/views/Asset/edit.html.twig, src/AppBundle/Resources/views/Asset/list.html.twig, src/AppBundle/Resources/views/Contact/_contact_form.html.twig, src/AppBundle/Resources/views/Contact/_contact_list.html.twig, src/AppBundle/Resources/views/Safeguard/edit.html.twig, src/AppBundle/Twig/FormFieldsExtension.php, tests/mocha/expandingtransactionstabletests.html
Copy changes when talking about 'the client'
=> Dd 1629 master

src/AppBundle/Resources/translations/user-details.en.yml
Update content to make clear user cannot amend their email address
themselves.
=> dd-1365-update-your-details-content

src/AppBundle/Resources/translations/report-decisions.en.yml
=> dd-1366-amend-capitalisation-decisions

src/AppBundle/Resources/translations/validators.en.yml
=> fix-typo-property

src/AppBundle/Resources/translations/validators.en.yml
Update error messages for style
=> dd-1409-review-error-messages

src/AppBundle/Resources/assets/javascripts/formatcurrency.js, src/AppBundle/Resources/assets/javascripts/iefix.js
(5,000 autotformatted to 5,5000 in IE 8), due to JS substr with negative numbers
=> fix comma problem 

src/AppBundle/Resources/translations/report-transactions.en.yml
=> DDPB-412-transfers-to-other-accounts

src/AppBundle/Resources/translations/report-transactions.en.yml
Content updated in light of Liz Feenan’s comments
=> DDPB 412 transfers to other accounts

Gulpfile.js, src/AppBundle/Resources/assets/scss/application-ie7.scss, src/AppBundle/Resources/assets/scss/application-ie8.scss, src/AppBundle/Resources/assets/scss/application.scss, src/AppBundle/Resources/views/Layouts/application.html.twig
css import replaced with external link reference
=> govuk template hotfix

src/AppBundle/Resources/translations/email.en.yml, src/AppBundle/Resources/translations/odr-account-form.en.yml, src/AppBundle/Resources/translations/odr-accounts.en.yml, src/AppBundle/Resources/translations/odr-action-gifts.en.yml, src/AppBundle/Resources/translations/odr-action-info.en.yml, src/AppBundle/Resources/translations/odr-action-property.en.yml, src/AppBundle/Resources/translations/odr-assets.en.yml, src/AppBundle/Resources/translations/odr-debts.en.yml, src/AppBundle/Resources/translations/odr-expenses.en.yml, src/AppBundle/Resources/translations/odr-homepage.en.yml, src/AppBundle/Resources/translations/odr-income-benefits.en.yml, src/AppBundle/Resources/translations/odr-overview.en.yml, src/AppBundle/Resources/translations/odr-visits-care.en.yml, src/AppBundle/Resources/translations/validators.en.yml, src/AppBundle/Resources/views/Components/Navigation/_odr-nav.html.twig, src/AppBundle/Resources/views/Email/odr-submission-confirm.html.twig, src/AppBundle/Resources/views/Email/odr-submission-confirm.text.twig, src/AppBundle/Resources/views/Odr/Formatted/formatted.html.twig, src/AppBundle/Resources/views/Odr/Formatted/formatted_body.html.twig, src/AppBundle/Resources/views/Odr/Index/_odr_row.html.twig, src/AppBundle/Resources/views/Odr/Index/review.html.twig, tests/phpunit/Resources/views/Odr/OdrFormattedTest.php
Opening renamed New, deputyship renamed deputy
=> DDPB-583 Rename ODR

src/AppBundle/Resources/translations/email.en.yml, src/AppBundle/Resources/views/Email/digideps-email-template.html.twig, src/AppBundle/Resources/views/Email/odr-submission-confirm.html.twig, src/AppBundle/Resources/views/Email/odr-submission-confirm.text.twig, src/AppBundle/Resources/views/Email/password-forgotten.text.twig, src/AppBundle/Resources/views/Email/report-submission-confirm.html.twig, src/AppBundle/Resources/views/Email/report-submission-confirm.text.twig, src/AppBundle/Resources/views/Email/user-activate.html.twig, src/AppBundle/Resources/views/Email/user-activate.text.twig
Have updated footer to reflect new content
=> DDPB 435 email content

src/AppBundle/Resources/assets/scss/digideps/_data-item.scss, src/AppBundle/Resources/views/Report/Report/index.html.twig, src/AppBundle/Resources/views/Report/_list-reports.html.twig
Refactored slightly the report page (Report/Report/index).
This included fixing the duplication of headings, the width of top heading (overlapping the helpline component) and the button/links layout.
=> ddpb-672 report page heading and layout

src/AppBundle/Resources/views/Report/Balance/_balance-bad.html.twig
Minor html tweaks for improved layout
=> Ddpb 513 accounts balance

src/AppBundle/Resources/translations/odr-homepage.en.yml, src/AppBundle/Resources/translations/settings.en.yml
@biggs Have rewritten help text on the homepage for your reports. Think it
makes more sense now.
=> DDPB-860-check-through-amends-to-NDR

src/AppBundle/Resources/translations/odr-actions.en.yml, src/AppBundle/Resources/translations/odr-assets.en.yml, src/AppBundle/Resources/translations/odr-debts.en.yml, src/AppBundle/Resources/translations/odr-income-benefits.en.yml, src/AppBundle/Resources/translations/odr-visits-care.en.yml, src/AppBundle/Resources/views/Odr/Asset/Property/step.html.twig, src/AppBundle/Resources/views/Odr/Debt/edit.html.twig, src/AppBundle/Resources/views/Odr/VisitsCare/step.html.twig
Hint texts added where needed in Actions, Assets, Debts,
Income/Benefits, Visits/Care
=> DDPB 819 add hint text to NDR

src/AppBundle/Resources/translations/odr-assets.en.yml, src/AppBundle/Resources/views/Odr/Asset/summary.html.twig
@Biggs, sdded WeAskAbout content to Assets for shortened Summary introduction.
Please check and wire up.
=> DDPB--820-WeAskAbout-content

src/AppBundle/Resources/translations/report-decisions.en.yml
@biggs Column heading 3 amended from:
How was client involved
to:
If not, explain why; if yes, provide detail
=> DDPB-765-decisions-column-heading-yes-no

src/AppBundle/Resources/translations/odr-actions.en.yml, src/AppBundle/Resources/translations/odr-bank-accounts.en.yml, src/AppBundle/Resources/translations/odr-debts.en.yml, src/AppBundle/Resources/translations/odr-declaration.en.yml, src/AppBundle/Resources/translations/odr-deputy-expenses.en.yml, src/AppBundle/Resources/translations/odr-income-benefits.en.yml, src/AppBundle/Resources/translations/odr-more-info.en.yml, src/AppBundle/Resources/translations/odr-submitted.en.yml, src/AppBundle/Resources/translations/odr-visits-care.en.yml, src/AppBundle/Resources/translations/report-gifts.en.yml, src/AppBundle/Resources/translations/report-more-info.en.yml
Have implemented Simon Busch’s content changes and created bug tickets
for the changes I wasn’t able to do in the translation files.
=> DDPB-978-check-content-changes-made-in-NDR

src/AppBundle/Resources/translations/odr-debts.en.yml
=> DDPB-981-NDR-debt-content-tweak

src/AppBundle/Resources/assets/scss/_shame.scss, src/AppBundle/Resources/assets/scss/digideps/_status.scss, src/AppBundle/Resources/views/Pa/settings.html.twig, src/AppBundle/Resources/views/Pa/team.html.twig
User accounts table built with dummy data.
=> DDPB-1026 user accounts list html and css. status-label styles.

src/AppBundle/Resources/assets/scss/digideps/_pagination.scss
=> DDPB-931 prev/next arrow showing in IE8

src/AppBundle/Resources/views/Pa/Team/list.html.twig
team list refined
’add user’ removed for pa user
hide stuff when info missing (job title and phone)
=> DDPB-1027 team list refinement

src/AppBundle/Resources/translations/odr-actions.en.yml, src/AppBundle/Resources/translations/report-gifts.en.yml
=> DDPB-1094-fix-gifts

src/AppBundle/Resources/translations/report-actions.en.yml
Content amended (fuller description in summary page of question asked)
=> DDPB-760-visits-and-care-summary

src/AppBundle/Resources/translations/report-gifts.en.yml
@biggs Gift hint text for report amended to reflect past gift-giving
=> DDPB-1094-fix-gifts-2

src/AppBundle/Resources/translations/report-balance.en.yml, src/AppBundle/Resources/translations/report-money-short.en.yml, src/AppBundle/Resources/translations/report-money-transaction.en.yml
Mentions of expense in 102 money out replaced with payment where
appropriate
=> DDPB-1119-fix-expenses-payments-bug

src/AppBundle/Resources/translations/report-actions.en.yml, src/AppBundle/Resources/translations/report-bank-accounts.en.yml
Guidance added to Actions you plan to take and Bank accounts
=> DDPB-1103-add-missing-guidance-to-102

Dockerfile, docker/confd/conf.d/beaver.application.conf.toml, docker/confd/templates/beaver.application.conf.tmpl
* Updated docker php-fpm to latest stable
*  Updated logging config to add stackname
Closes #614
=> Opgops 1883

src/AppBundle/Service/WkHtmlToPdfGenerator.php
This was an encoding problem when creating the PDF. I have fixed this and pound signs and special characters now render correctly
=> DDPB-1172: Fixing encoding on PDF generation

tests/behat/features/deputy/01-registration-steps/04-add-client-and-report.feature, tests/behat/features/pa/02-dashboard.feature
Seems that the links were already in place so the only change was to add behat tests to verify
=> DDPB-1145: Behat tests to verify links in header for lay and pa

src/AppBundle/Resources/views/Report/Formatted/Accounts/_money_in_out_short.html.twig
=> DDPB-1216: Added missing £ sign

src/AppBundle/Form/YesNoType.php
=> DDPB-1515 add validation group default into the yesno form

src/AppBundle/Resources/translations/report-overview.en.yml, src/AppBundle/Resources/views/Macros/macros-review.html.twig, src/AppBundle/Resources/views/Odr/Odr/overview.html.twig
Client's welfare > Health and welfare, show empty yes/no questions in review report/pdf
=> DDPB-1593 104 bugfixes

src/AppBundle/Resources/assets/scss/digideps/formatted_report/_main.scss, src/AppBundle/Resources/assets/scss/extensions/elements/_forms.scss
fixed the overlapping header/content issue.
=> DDPB-304 rows not allowed to page-break.

src/AppBundle/Resources/translations/client-contacts.en.yml, src/AppBundle/Resources/translations/client-notes.en.yml, src/AppBundle/Resources/translations/pa-team.en.yml, src/AppBundle/Resources/translations/registration.en.yml, src/AppBundle/Resources/translations/report-documents.en.yml, src/AppBundle/Resources/translations/settings.en.yml, src/AppBundle/Resources/translations/user-account.en.yml, src/AppBundle/Resources/translations/user-activate.en.yml, src/AppBundle/Resources/views/Client/add.html.twig, src/AppBundle/Resources/views/Pa/ClientProfile/deleteConfirm.html.twig, src/AppBundle/Resources/views/Pa/ClientProfile/deleteContactConfirm.html.twig, src/AppBundle/Resources/views/Pa/Team/add.html.twig, src/AppBundle/Resources/views/Pa/Team/deleteConfirm.html.twig, src/AppBundle/Resources/views/Pa/Team/edit.html.twig, src/AppBundle/Resources/views/Report/Document/deleteConfirm.html.twig, src/AppBundle/Resources/views/Report/Report/create.html.twig, src/AppBundle/Resources/views/Settings/index.html.twig, src/AppBundle/Resources/views/Settings/passwordEdit.html.twig, src/AppBundle/Resources/views/Settings/passwordEditDone.html.twig, src/AppBundle/Resources/views/Settings/profile.html.twig, src/AppBundle/Resources/views/Settings/profileEdit.html.twig, src/AppBundle/Resources/views/User/activate.html.twig, src/AppBundle/Resources/views/User/details.html.twig, src/AppBundle/Resources/views/User/edit.html.twig
h1Title is not used anymore. Replacing with pageTitle.
=> h1Title > pageTitle

src/AppBundle/Controller/Odr/AssetController.php, src/AppBundle/Controller/Odr/BankAccountController.php, src/AppBundle/Controller/Odr/DebtController.php, src/AppBundle/Controller/Odr/DeputyExpenseController.php, src/AppBundle/Controller/Report/ActionController.php, src/AppBundle/Controller/Report/AssetController.php, src/AppBundle/Controller/Report/DebtController.php, src/AppBundle/Controller/Report/DeputyExpenseController.php, src/AppBundle/Controller/Report/GiftController.php, src/AppBundle/Controller/Report/LifestyleController.php, src/AppBundle/Controller/Report/MoneyInShortController.php, src/AppBundle/Controller/Report/MoneyOutShortController.php, src/AppBundle/Controller/Report/MoneyTransferController.php, src/AppBundle/Controller/Report/PaFeeExpenseController.php, src/AppBundle/Form/Odr/DebtsType.php, src/AppBundle/Form/Pa/TeamMemberAccountType.php, src/AppBundle/Form/Report/ActionType.php, src/AppBundle/Form/Report/FeesType.php, src/AppBundle/Form/Report/OtherInfoType.php, src/AppBundle/Form/Report/TransactionsType.php, src/AppBundle/Form/YesNoType.php
More updates in the wake of ticket 1410 - Fixes for passing translation_domain through into configureOptions
=> Ddpb 1757b missing question

src/AppBundle/Resources/assets/scss/digideps/formatted_report/_main.scss, src/AppBundle/Resources/views/Report/Formatted/_report_summary.html.twig
'internal use only' added, 'cash' > 'liquid assets', includes list
=> DDPB-1759 tweaks

src/AppBundle/Resources/translations/common.en.yml, src/AppBundle/Resources/translations/report-display.en.yml, src/AppBundle/Resources/views/Odr/Odr/review.html.twig, src/AppBundle/Resources/views/Report/Report/review.html.twig
submitted content and buttons for ndr and report, lay/PA content as well (for button)
=> DDPB-1859 new content for review page for submitted reports

src/AppBundle/Controller/Report/DebtController.php
=> DDPB-2117-debt-notification-yesno-remove

src/AppBundle/Resources/views/Admin/Client/Report/checklist.html.twig, src/AppBundle/Resources/views/Report/Asset/_list.html.twig
=> DDPB-2161 documents on checklist. assets trans fix.

Dockerfile, src/AppBundle/Controller/Report/ReportController.php, src/AppBundle/Resources/views/Org/ClientProfile/_contacts.html.twig, src/AppBundle/Resources/views/Org/ClientProfile/_notes.html.twig, src/AppBundle/Resources/views/Org/ClientProfile/_reportDetail.html.twig, src/AppBundle/Resources/views/Org/ClientProfile/_subsection.html.twig, src/AppBundle/Resources/views/Org/ClientProfile/overview.html.twig, src/AppBundle/Resources/views/Report/Report/overview.html.twig, tests/behat/features/pa/03-report/05-report-resubmission.feature
Fixes:
1. Statuses on the active report (below)
2. Duplicate IDs removed
3. Client profile page always showing both reports
4. Test failures
=> Ddpb 2253 fixes

src/AppBundle/Resources/views/Report/Formatted/Accounts/_final_summary.html.twig, src/AppBundle/Resources/views/Report/Formatted/_prof_deputy_costs.html.twig
https://opgtransform.atlassian.net/browse/DDPB-2383
=> DDPB-2383: Fixes PDF report hardcoded Client and balance total

src/AppBundle/Controller/Org/TeamController.php, src/AppBundle/Resources/views/Org/Team/list.html.twig
https://opgtransform.atlassian.net/browse/DDPB-2415
=> DDPB 2415 pro deputies list timeout

app/config/services/resolvers.yml, src/AppBundle/Controller/Report/ProfDeputyCostsController.php, src/AppBundle/Resolver/SubSectionRoute/ProfCostsSubSectionRouteResolver.php, tests/behat/features/prof/03-report/05-deputy-costs.feature
https://opgtransform.atlassian.net/browse/DDPB-2437
=> DDPB 2437 redirect to subsection of section

src/AppBundle/Entity/Report/ProfDeputyEstimateCost.php, src/AppBundle/Entity/Report/ProfDeputyOtherCost.php, src/AppBundle/Form/Report/ProfDeputyEstimateCostSingleType.php, src/AppBundle/Form/Report/ProfDeputyOtherCostSingleType.php, src/AppBundle/Resources/translations/validators.en.yml, tests/behat/features/prof/03-report/05-deputy-costs.feature, tests/behat/features/prof/03-report/06-deputy-code-estimates.feature
=> DDPB 2438 nested form validation

src/AppBundle/Resources/views/Ndr/Formatted/_visits-care.html.twig, src/AppBundle/Resources/views/Ndr/Formatted/formatted_body.html.twig, src/AppBundle/Resources/views/Report/Formatted/_visits_care.html.twig
Used the same translation on the report summary / pdf as on the
questions to make the wording consistent for care plan question
=> DDPB-2453 Change wording to make consistent for care plan pdf

src/AppBundle/Resources/views/Index/privacy.html.twig, src/AppBundle/Resources/views/Index/terms.html.twig
Updates the Terms of use and Privacy notice to match new suggested wording.
=> DDPB-2411 Implement new Digi Deps Privacy Policy & T&Cs

src/AppBundle/Controller/Admin/Client/ReportController.php
Removed duplicate code and put condition to not show if notice
already there for checklist saved. Probably did something silly
as it's b/e code. But thought I'd give it a shot.
=> DDPB-2387 Remove duplicate flash notice on checklist

src/AppBundle/Resources/translations/admin.en.yml, src/AppBundle/Resources/views/Admin/Stats/stats.html.twig
https://opgtransform.atlassian.net/browse/DDPB-2514
=> DDPB-2514: Removes CSV stats download link

src/AppBundle/Resources/views/Admin/Client/Report/checklist.html.twig
This was agreed as the solution with Phil to use the same
treatment to make the box expandable and clear.
=> DDPB-2466 Use same JS for other checklist textbox

tests/behat/features/deputy/02-ndr/10-submit.feature, tests/behat/features/deputy/03-report/01-102/21-check-and-submit.feature, tests/behat/features/deputy/03-report/01-102/23-report-resubmission.feature, tests/behat/features/deputy/03-report/01-102/24-lodging-checklist.feature, tests/behat/features/deputy/04-user/06-codeputies.feature, tests/behat/features/deputy/05-acl/02-pages-security.feature
Cherry-picks #1170 and fixes an issue with tests using invalid dates
=> DDPB-2517: Add new users to feature-105 branch

src/AppBundle/Resources/views/Admin/Client/Report/checklist.html.twig, src/AppBundle/Resources/views/Admin/Client/Report/partials/_deputy-and-client-info.html.twig, src/AppBundle/Resources/views/Admin/Client/Report/partials/_money-in-and-out.html.twig, src/AppBundle/Resources/views/Layouts/moj_template.html.twig
Errors and warnings fixed for checklist, one remains for code
required by SF bar.
=> DDPB-2481 Fix HTML validation where possible

src/AppBundle/Entity/Report/Checklist.php, src/AppBundle/Form/Admin/ReportChecklistType.php, src/AppBundle/Resources/translations/admin-checklist.en.yml, src/AppBundle/Resources/translations/validators.en.yml, src/AppBundle/Resources/views/Admin/Client/Report/Formatted/checklist_formatted_body.html.twig, src/AppBundle/Resources/views/Admin/Client/Report/partials/_money-in-and-out.html.twig, src/AppBundle/Resources/views/Admin/Client/Report/partials/_pa-fee-expenses.html.twig, tests/behat/features/pa/03-report/06-lodging-checklist.feature
On the checklist "View deputy expenses" was shown twice. Got rid
of the one in the money in/out section. Also added a new question
on the checklist for PA.
=> DDPB-2412 Remove duped deputy expense list and add new question

src/AppBundle/Resources/assets/scss/digideps/_status.scss, src/AppBundle/Resources/translations/common.en.yml, src/AppBundle/Resources/translations/report-overview.en.yml, src/AppBundle/Resources/views/Org/ClientProfile/_reportDetail.html.twig, src/AppBundle/Resources/views/Org/Index/dashboard.html.twig, src/AppBundle/Resources/views/Report/Report/_header.html.twig, src/AppBundle/Resources/views/Report/Report/overview.html.twig
Had to make a new PR for this work as the I encountered a similar problem to Greg where `HACK-SOLUTION0.1` commit ended up in my commit history when pulling in master 🙈 
I've simplified this a lot since last PR reviews as it turned out that returning a status of `changesNeeded` from the api was leading to all sorts of unintended confusion client side when it came to counting reports, showing the correct status and having reports appear in the correct status column in the dashboard.
Now I'm determining the status based on `unSubmitDate` and `submitted`.
=> Ddpb 2537 rename unnamed pa prof reports

docker/confd/templates/behat.yml.tmpl, src/AppBundle/Resources/views/Admin/ReportSubmission/index.html.twig, src/AppBundle/Resources/views/Report/Report/overview.html.twig, src/AppBundle/Resources/views/Report/Report/review.html.twig, tests/behat/features/admin/00-prechecks.feature, tests/behat/features/admin/01-admin.feature, tests/behat/features/deputy/01-registration-steps/00-prechecks.feature, tests/behat/features/deputy/02-ndr/10-submit.feature, tests/behat/features/deputy/03-report/01-102/21-check-and-submit.feature, tests/behat/features/deputy/04-user/00-login-logout.feature, tests/behat/features/deputy/07-infra-checks/00-documents.feature
Adds a new test suite for infrastructure tests, allowing quick smoke tests when making infra changes
=> DDPB-2572: Minimal infrastructure test suite

package-lock.json, package.json
Output **after** running `npm audit fix`.
```
[opg-digi-deps-client](DDPB-2627-npm-security-fixes)$ npm audit
=== npm audit security report ===
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Regular Expression Denial of Service                         │ …
```
=> DDPB-2627: Updates npm dependencies after npm audit fix

.github/pull_request_template.md, Dockerfile, Gulpfile.js, bin/security-checker, composer.lock
We want to implement a PR template to ensure that we're following best practices and implementing our [Definition of Done](https://opgtransform.atlassian.net/wiki/spaces/DEPDS/pages/1041006647/DRAFT+-+Team+Charter#DRAFT-TeamCharter-7.DefinitionofDone) when making changes to our repositories.
I've created a pull request template to GitHub which will be automatically used when future pull requests are created. This provides prompts to help describe what's changed and a convenient checklist to sign post developers to ensure our standards are being enforced.
You can see the template rendered [here](https://github.com/ministryofjustice/opg-digi-deps-client/blob/support-pr-template/.github/pull_request_template.md).
I took the Purpose/Approach/Learning idea from another [GitHub …
=>  Create pull request template

app/config/config.yml
Reverts ministryofjustice/opg-digi-deps-client#1236
Testing complete
=> Revert "Disable CSRF protection for infrastructure testing"

app/Resources/TwigBundle/views/Exception/template.html.twig, src/AppBundle/Resources/assets/scss/digideps/_forms.scss, src/AppBundle/Resources/views/Components/Form/_input.html.twig, src/AppBundle/Resources/views/Layouts/application.html.twig, src/AppBundle/Resources/views/Layouts/moj_template.html.twig
Addresses some small design issues highlighted in release of DDPB-2646.
1. Increased padding at bottom of input prefix
1. Fixed typo with CSS class concatenation
1. Move details banner above wrapper
- N/A
- There is, but ignoring for this patch release (it's dev-side anyway)
=> DDPB-2646: Fix some minor design issues 

src/AppBundle/Resources/assets/scss/digideps/_cards.scss, src/AppBundle/Resources/views/Ndr/Ndr/_ndr_row.html.twig, src/AppBundle/Resources/views/Ndr/Ndr/_report_row.html.twig, src/AppBundle/Resources/views/Report/Report/_report_row.html.twig
_Briefly describe the purpose of the change, and/or link to the JIRA ticket for context_
Fixes [DDPB-2702](https://opgtransform.atlassian.net/browse/DDPB-2702)
_Explain how your code addresses the purpose of the change_
_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about DigiDeps_
=> DDPB-2702: refactors card css component inline with govuk-frontend

src/AppBundle/Resources/assets/scss/_digideps.scss, src/AppBundle/Resources/assets/scss/digideps/_pager.scss, src/AppBundle/Resources/assets/scss/digideps/_pagination.scss, src/AppBundle/Resources/views/Components/paginator.html.twig, src/AppBundle/Resources/views/Report/_nextprevious.html.twig
Upgrade `.pagination` CSS to Design System standards
Fixes [DDPB-2709](https://opgtransform.atlassian.net/browse/DDPB-2709)
- Split code into two separate files
- Simplified CSS a lot
- Used GDS mixins and variables
Deferred to #1269
=> DDPB-2709: Upgrade `.pagination` CSS to Design System standards

docs/PULL_REQUEST_TEMPLATE.md
There are various standards we have for the quality of our frontend. These cannot be automatically enforced due to many situations where deviations are acceptable.
I've added checks against these standards to the PR template. This reminds developers to try and meet them, without rigorous enforcement.
I added these under a new "For each page changed" section to indicate that they need to be reviewed on each individual page rather than the application as a whole.
[Rendered](https://github.com/ministryofjustice/opg-digi-deps-client/blob/e9491e016f0d19556e0f8fee8dd82ecd600e6ba5/docs/PULL_REQUEST_TEMPLATE.md)
In the future we should try and automate more of this. We should also take lessons from the Accessibility and Testing COPs to ensure we're aligned with departmental standards.
=> Add checklist steps for frontend page changes
