- src/AppBundle/Controller/ReportController.php
- src/AppBundle/Resources/views/Report/display.html.twig
- src/AppBundle/Resources/views/Report/formatted.html.twig
viewing old reports added before safeguarding produced an error when the user tried to view them. This is because they did not pass the validation rules for a new report and there was no check to see if a safeguarding value was null or not.
> DD-1094. Fixed viewing old reports

- src/AppBundle/Controller/IndexController.php
- src/AppBundle/Resources/assets/javascripts/sessionTimeoutDialog.js
@ztolley I've changed the keep alive URL to be a GET, Firefox was otherwise asking to confirm with an additional popup to submit (POST) the data. It initially was a POST to avoid potential proxy caching, but I've added a timestamp to the URL so that won't be a problem
> session keep alive no popup on ff

- Dockerfile
This change will ensure javascript is gzipped in transit. It uses a container that incorporates the following change:
https://github.com/ministryofjustice/opg-docker/commit/88b0fef40ddf4fe02d7a9f14389b970097dbec05
@elvisciotti - this is the change that we discussed on Slack (2016-09-28 11:56)
> Updated base container to one with the fix to gzip javascript

- src/AppBundle/Resources/views/Layouts/application.html.twig
This fixes a layout issue on IE8
> DDPB-926 added missing css refs to govuk template ie7 and ie8.

- src/AppBundle/Resources/views/Layouts/application.html.twig
- src/AppBundle/Resources/views/Layouts/moj_template.html.twig
IE8 radio buttons and checkboxes were failing because application.css was being loaded as well as application-ie8.css. I updated all the link refs to match a more modern version of gov.uk. This fixes the loading issue.
Also removed a legacy font loader:
https://github.com/alphagov/govuk_template/pull/219
Shifted the stylesheets into moj_template. No need to keep them in application.
Tested in a feature branch, looks good.
> DDPB-929 modernising head link refs, esp ie conditionals.

- src/AppBundle/Resources/assets/javascripts/modules/submit.js
Added javascript to disable the form submit buttons after submission. This prevents the creation of duplicate entries in most cases.
It's not watertight. Ideally we'd use a single use token in the form to make the requests idempotent but that's outside the scope of this ticket.
You may need to run docker exec -it opgdigidepsdocker_frontend_1 gulp to test this locally.
> DDPB-1165: JavaScript fix for duplicate form submissions

- app/config/security.yml
- tests/behat/bootstrap/AuthenticationTrait.php
- tests/behat/features/pa/07-acl.feature
I checked the controllers in the API and they seem to have the correct security set up. Either they are only accessible by non PA users or they verify that you own the id of the user you are trying to edit.
> DDPB-1204: ACL for client settings plus behat tests

- src/AppBundle/Controller/Report/ReportController.php
- src/AppBundle/Resources/views/Email/report-submission-confirm.html.twig
- src/AppBundle/Resources/views/Email/report-submission-confirm.text.twig
- src/AppBundle/Service/Mailer/MailFactory.php
- tests/phpunit/Service/Mailer/MailFactoryTest.php
PA submission email now has the PDF attached. I've also reworded the email text to reflect this.
Tested and this works correctly. Email received containing the pdf.
All behat tests pass locally.
> DDPB-1209: Attach submitted report pdf to PA email

- src/AppBundle/Controller/Report/BankAccountController.php
- src/AppBundle/Entity/Odr/BankAccount.php
- src/AppBundle/Entity/Report/BankAccount.php
- src/AppBundle/Form/Odr/BankAccountType.php
- src/AppBundle/Form/Report/BankAccountType.php
- src/AppBundle/Resources/views/Odr/BankAccount/_list.html.twig
- src/AppBundle/Resources/views/Odr/BankAccount/step.html.twig
- src/AppBundle/Resources/views/Odr/Formatted/_accounts.html.twig
- src/AppBundle/Resources/views/Report/BankAccount/_list.html.twig
- src/AppBundle/Resources/views/Report/BankAccount/step.html.twig
- src/AppBundle/Resources/views/Report/Formatted/Accounts/_summary.html.twig
- src/AppBundle/Resources/views/Report/MoneyTransfer/_list.html.twig
- tests/behat/features/pa/05-edit-report-sections.feature
Co-dependency on the API PR https://github.com/ministryofjustice/opg-digi-deps-api/pull/341
There was an assumption that bank account types which didn't require a sort code ALSO didn't require a bank account name, but this is incorrect: the type 'other_no_sortcode' requires no sort code but still requires a bank name
SO work done to turn the requiresBankNameAndSortCode() function into separate requiresBankName() and requiresSortCode() functions
> Ddpb 750 bank account name

- tests/behat/features/pa/05-edit-report-sections.feature
To prevent money transfers option showing up and preventing the report submission in a later test. It’s an opportunity to test delete functionality anyway
> Remove 2 added bank accounts after testing

- Dockerfile
This PR aims to shrink the ```docker build .``` times to negative values.
Not there yet, but locally I achieved some good results:
my baseline
On jenkins, the 01_Build_Docker_Images job averages around 30minutes
locally:
```
time docker build --no-cache .
real    12m6.638s
user    0m1.421s
sys     0m0.133s
```
with these changes:
```
time docker build --no-cache .
real    4m34.245s
user    0m1.459s
sys     0m0.196s
```
Jenkins jobs:
(24min) with only the changes from this PR:
https://jenkins.service.opg.digital/job/Digi-Deps/job/01_Build_Docker_Images/654/console
(13min) with these changes + https://github.com/ministryofjustice/opg-digi-deps-docker/pull/60
https://jenkins.service.opg.digital/job/Digi-Deps/job/01_Build_Docker_Images/652/console
> DDPB-1764: reduce docker build times

- Dockerfile
- Dockerfile.base
See: ministryofjustice/opg-digi-deps-docker#61
This PR splits the Dockerfile into a nightly build using a Dockerfile.base and the normal build which will consume a FROM: nnnnn-base:nightly.
> DDPB-1764: split Dockerfile and add a nightly Dockerfile.base

- src/AppBundle/Resources/views/Report/Report/_subsection.html.twig
Reverts some of the frontend changes made on 30th Nov 2017 in association with DDPB-1758 to reinstate an <a> tag around the whole subsection. Otherwise the page is broken with the “Edit” links set to display:none (mobile view)
> DDPB-1840 Mobile links broken hotfix

- src/AppBundle/Resources/views/Admin/Client/Report/Formatted/checklist_formatted_body.html.twig
Lifestyle was showing in a different place for 104-3 reports than
on the checklist, so it should match the order on the checklist
now.
> DDPB-2384 Move lifestyle below visits and care

- src/AppBundle/Resources/views/Report/Formatted/Accounts/_final_summary.html.twig
The financial summary is counting deputy costs twice (as costs
and in money out) - this is fixed here so money out is separate.
> DDPB-2405 Fix money out in financial summary preview

- src/AppBundle/Resources/views/Report/Formatted/_prof_deputy_costs_estimate.html.twig
For deputy estimates when not filled in preview was showing an
empty translation key. This is now only shown if there is an
option selected for how charge.
> DDPB-2405 Don't show empty translation for howcharged

- src/AppBundle/Controller/Admin/StatsController.php
Something I noticed whilst fixing DDPB-2442. There is potential for a filename clash due to 12 hour format, so worth a quick fix whilst fixing 2442.
> DDPB-2442: Downloads Report Submission .dat files in 24 hour format

- src/AppBundle/Resources/translations/report-documents.en.yml
- src/AppBundle/Resources/views/Report/Document/start.html.twig
Changes the warning message on the supported documents page for professional deputies, prompting them to upload a cost certificate.
> DDPB-2459 Request cost certificate from professional deputies

- src/AppBundle/Entity/Report/Traits/ReportProfDeputyCostsTrait.php
- src/AppBundle/Form/Report/ProfDeputyCostHowType.php
- src/AppBundle/Resources/translations/report-prof-deputy-costs.en.yml
- src/AppBundle/Resources/views/Report/Formatted/_prof_deputy_costs.html.twig
- src/AppBundle/Resources/views/Report/ProfDeputyCosts/_how_charged_answers.html.twig
- src/AppBundle/Resources/views/Report/ProfDeputyCosts/howCharged.html.twig
- tests/behat/features/prof/03-report/05-deputy-costs.feature
- tests/phpunit/Resources/views/Report/FormattedTest.php
This removes all references to "Agreed costs" in the deputy costs section of the report. It removes the option from forms, output and summary, and also from any related tests.
This should be merged before [the API/DB changes](https://github.com/ministryofjustice/opg-digi-deps-api/pull/509) to ensure the client isn't making reference to deleted fields.
> DDPB-2468 Remove Agreed costs option from 105

- src/AppBundle/Controller/Report/ProfDeputyCostsEstimateController.php
- src/AppBundle/Controller/Report/ReportController.php
- src/AppBundle/Entity/Report/Traits/ReportProfDeputyCostsEstimateTrait.php
- src/AppBundle/Resources/views/Report/Formatted/_prof_deputy_costs_estimate.html.twig
- src/AppBundle/Resources/views/Report/ProfDeputyCostsEstimate/_answers.html.twig
- tests/behat/features/prof/03-report/06-deputy-code-estimates.feature
Comparing to the previous branch in this piece of work (`Feature/DDPB-2458`) until its merged. Once `Feature/DDPB-2458` is merged I'll update the base branch to `feature-105`.
I don't see any tests related to the actual contents of the PDF preview so I've not added any assertions for that - if anyone thinks theres value in that let me know I can add something in.
> Feature/DDPB-2458 - Add general management figure to summary, Preview page and PDF

- app/config/parameters.yml.dist
- app/config/services.yml
- docker/confd/conf.d/parameters.hml.toml
- docker/confd/templates/parameters.yml.tmpl
Currently the html to pdf container address is hardcoded. This change uses an address passed in from an env var, and allows us to isolate the containers and change them independently.
> DDPB-2491 Allow wkhtmltopdf host address to be configured

- tests/behat/features/prof/03-report/06-deputy-code-estimates.feature
An extra `ƒ` had snuck into the feature file, causing the command not to be matched and the tests to fail.
> Remove a misplaced character which was causing behat tests to fail

- src/AppBundle/Entity/Report/Traits/ReportProfDeputyCostsEstimateTrait.php
- src/AppBundle/Form/Report/ProfDeputyEstimateCostsType.php
- tests/behat/features/prof/03-report/06-deputy-code-estimates.feature
As the form field didn't have grouping applied to it and the expected type was a `double`, validation errors were preventing any figure with 4 digits or more being entered for management costs as the field formatting would add a `,` when submitting the value in the POST.
> Validation fix

- src/AppBundle/Controller/Report/ProfDeputyCostsController.php
- src/AppBundle/Resolver/SubSectionRoute/ProfCostsSubSectionRouteResolver.php
- tests/behat/features/prof/03-report/05-deputy-costs.feature
Stops deputies from being directed to the SCCO question if their costs are fixed.
Stops in two places:
- Clicking through from the report summary
- Pressing "Back" on the deputy costs breakdown screen
>  DDPB-2506: Deputy costs asking for SCCO figure with fixed costs

- src/AppBundle/Resources/translations/admin-checklist.en.yml
- src/AppBundle/Resources/views/Admin/Client/Report/Formatted/checklist_formatted_body.html.twig
Add translation text and fix usage of `trans`
> DDPB-2467: Fix translation for `totalEstimatedCosts` label

- src/AppBundle/Entity/Report/Traits/ReportProfDeputyCostsTrait.php
- src/AppBundle/Validator/Constraints/EndDateNotBeforeStartDateValidator.php
I've had to rejig the validation callback function here as if we had a valid value in amount but an invalid value in date we were still getting a validation error for the amount due to the  `!empty($ic->getAmount()) && !empty($ic->getDate()` check. 
I'd taken the intent of the function to be checking for just one interim cost and associated date to exist hence why I dropped the `foreach` and moved to checking the first index of the `interimCosts` array.
> DDPB-2465 fix validation errors

- tests/behat/features/deputy/02-ndr/10-submit.feature
- tests/behat/features/deputy/03-report/01-102/21-check-and-submit.feature
- tests/behat/features/deputy/03-report/01-102/23-report-resubmission.feature
- tests/behat/features/deputy/03-report/01-102/24-lodging-checklist.feature
- tests/behat/features/deputy/05-acl/02-pages-security.feature
In DDPB-2517, we are adding new fixture users so that testers can easily log in as professional and PA deputies. We also auto-populate some reports to ensure they are accessible by testers.
These changes requires automated feature tests to be updated to account for the new records. This occurs in two ways:
* Updating the count of clients
* Updating the ID of reports to account for the auto-generated ones
Admittedly these are "magic numbers" tests, and probably not what we want to be doing. However, these changes aren't adding new magic numbers, and they put us in a better position to refactor our tests going forward (for example by using fixture users rather than ones created in tests).
> DDPB-2517: Account for additional users/clients/reports in feature tests

- src/AppBundle/Resources/translations/report-assets.en.yml
- src/AppBundle/Resources/translations/report-debts.en.yml
- src/AppBundle/Resources/translations/report-visits-care.en.yml
- src/AppBundle/Resources/views/Macros/macros-review.html.twig
- src/AppBundle/Resources/views/Ndr/Formatted/_visits-care.html.twig
- src/AppBundle/Resources/views/Report/Formatted/_assets.html.twig
- src/AppBundle/Resources/views/Report/Formatted/_debts.html.twig
- src/AppBundle/Resources/views/Report/Formatted/_visits_care.html.twig
Some translations had to be modified and used as before they
weren't on the macro for visits and care. Transoptions passed in
so we can use translations for the strings. Mainly so that we
can see the client name on the review / pdf instead of
"the client"
> DDPB-2331 Change to use client name for visits and care

- src/AppBundle/Controller/SettingsController.php
Plenty of ways to fix this, but the quickest win is to just return straight to the template when a non Lay user is at the page - only Lay user's need to do the API lookup to extract client information, which is the cause of the unnecessary bottleneck for non Lay's.
> DDPB-2551: improves performance of Settings index for Org deputies

- src/AppBundle/Resources/views/Org/ClientProfile/overview.html.twig
So that they can see the client details easily when choosing a
client from the dashboard.
> DDPB-2535 Move client details for prof to top of client overview

- src/AppBundle/Resources/translations/ndr-bank-accounts.en.yml
- src/AppBundle/Resources/translations/report-bank-accounts.en.yml
- src/AppBundle/Resources/views/Ndr/BankAccount/step.html.twig
- src/AppBundle/Resources/views/Report/BankAccount/_list.html.twig
- src/AppBundle/Resources/views/Report/BankAccount/step.html.twig
- tests/behat/features/deputy/03-report/01-102/21-check-and-submit.feature
Replaces the prompt on the accounts page of a second report to make it clearer when only the closing balance needs updating.
Also updates the page title on accounts section to reflect whether you're adding a new or editing an existing account.
> DDPB-2553: Add a closing balance in Accounts section

- tests/behat/features/admin/04-case-manager.feature
- tests/behat/features/deputy/02-ndr/10-submit.feature
- tests/behat/features/deputy/03-report/01-102/21-check-and-submit.feature
- tests/behat/features/deputy/03-report/01-102/23-report-resubmission.feature
- tests/behat/features/deputy/03-report/01-102/24-lodging-checklist.feature
- tests/behat/features/deputy/05-acl/02-pages-security.feature
- tests/behat/features/pa/04-dashboard-client-profile/13-settings.feature
- tests/behat/features/prof/04-dashboard-client-profile/13-settings.feature
Fixes tests which have dependencies on fixtures which have changed:
- Removing unnecessary magic number tests
- Updating magic numbers in other tests
- Updating references to changed fixture data (e.g. login email addresses)
> DDPB-2524: Update tests to account for fixture user changes

- docker/confd/templates/behat.yml.tmpl
- scripts/clienttest.sh
- tests/behat/features/deputy/02-ndr/10-submit.feature
- tests/behat/features/deputy/03-report/01-102/11-expenses.feature
- tests/behat/features/deputy/03-report/01-102/12-gifts.feature
- tests/behat/features/deputy/03-report/01-102/17-money.feature
- tests/behat/features/deputy/03-report/01-102/19-transfers.feature
- tests/behat/features/deputy/03-report/01-102/21-check-and-submit.feature
- tests/behat/features/deputy/03-report/01-102/23-report-resubmission.feature
- tests/behat/features/deputy/04-user/00-login-logout.feature
- tests/behat/features/deputy/05-acl/02-pages-security.feature
- tests/behat/features/deputy/06-static-pages/04-privacy.feature
- tests/behat/features/deputy/07-infra-checks/00-documents.feature
Infrastructure tests provide a good "early warning system" to identify problems with the infrastructure. Running them first allows us to be confident that any changes to infrastructure have been successful without having to wait for the entire suite(s) to finish.
However, running them before all other tests means having to tweak later tests to account for the new data in the system. For example, tests which rely on a report having ID "5" now need to use ID "7" because of the two new reports inserted by infrastructure tests.
In some circumstances I've had to update magic number tests (which I've now tagged `@magic` for future fixing), but I've mostly tried to rewrite tests so they don't rely on previous tests/suites having been completed.
> DDPB-2576: Run infrastructure feature tests first

- src/AppBundle/Resources/views/Ndr/Ndr/_ndr_row.html.twig
- src/AppBundle/Resources/views/Ndr/Ndr/_report_row.html.twig
- tests/behat/bootstrap/UserTrait.php
- tests/behat/features/admin/05-ndr-enablement.feature
Adds Behat tests to verify that when NDR is enabled for a Deputy, that the Deputy can log in and has access to a new NDR. When disabled, access to the NDR is removed. And if re-enabled, access to the _previous_ NDR is recovered.
Added a catch all behat method to create, register, and activate a user.
> DDPB 2631 NDR creation on enabling

- tests/behat/features/deputy/04-user/06-codeputies.feature
There is a warning on [automated tests](https://jenkins.service.opg.digital/job/Digi-Deps/view/Master/job/Test_Master/128/consoleFull) about a call to the deprecated "I reset the email log" test step. This doesn't cause the test suite to fail.
I removed the line since it doesn't now do anything.
- [N/A] I have updated documentation (Confluence/GitHub wiki) where relevant
- [N/A] I have successfully built my branch to a feature environment
- [N/A] There are no new frontend linting errors (`docker-compose run --rm npm run lint`)
- [N/A] There are no NPM security issues (`docker-compose run --rm npm audit`)
- [N/A] There are …
> Remove deprecated 'reset the email log' command

- src/AppBundle/Resources/views/Layouts/application.html.twig
- tests/behat/features/deputy/06-static-pages/02-cookie-policy.feature
Follwing .gov.uk change to the cookie page from /cookies to /cookie-details, this branch fixes our behat tests and main template which contains the cookie link.
Ive updated the linkto be the correct page and updated the tests accordingly. Ive replaced the tests to reference the actual page whereas another approach might be to just test for a 200 response. However I have adopted an approach whereby we would want this test to fail in the event of any external changes to gov.uk so we can verify the page content is still applicable to the link we are generating on DD.
If these tests fail in the future, we need to check that the gov.uk site still contains relevant content
- [n/a] I have updated documentation (Confluence/GitHub wiki) where relevant
> Ddpb 2655 cookie link tests fix

- src/AppBundle/Form/Admin/ReportChecklistType.php
- src/AppBundle/Resources/views/Admin/Client/Report/Formatted/checklist_formatted_body.html.twig
- tests/behat/features/prof/03-report/08-lodging-checklist.feature
Adds an N/A option for a question on the checklist.
Fixes [DDPB-2602](https://opgtransform.atlassian.net/browse/DDPB-2602)
A straightforward copy and paste approach of other N/A options on the checklist
None
- [N/A] I have updated documentation (Confluence/GitHub wiki) where relevant
- [TBC] I have successfully built my branch to a feature environment
- [TBC] The product team have tested these changes
> DDPB-2602: Adds NA option to deputy costs section of checklist

- web/app.php
The check on FRONTEND_TEST_ENABLED is not strong enough: setting the variable to variable to "false" caused failures
Strengthen check on FRONTEND_TEST_ENABLED environment variable
> Strengthen check on FRONTEND_TEST_ENABLED environment variable

- src/AppBundle/Resources/views/Layouts/application.html.twig
- src/AppBundle/Resources/views/Org/ClientProfile/_detailsBanner.html.twig
The `details-banner` class is being used across the board, but it shouldn't be applied to lay deputy pages. Where it is, it's creating unnecessary whitespace and pushing the page content down:
Fixes [DDPB-2621](https://opgtransform.atlassian.net/browse/DDPB-2621)
As suggested in ticket, I removed the `details-banner` container when the user isn't a PA or professional deputy.
I identified one area where this doesn't work, which is the registration pages where it overlaps with the progress bar:
The reason this is an issue is that the registration pages are the only ones without a title, which would usually balance the left-hand side. To fix it then, I rearranged those pages to put the title above the progress bar:
I think this new layout is just as readable and more consistent. Since the …
> DDPB-2621: Remove 'details-banner' wrapper div for non pa/prof deputies

- src/AppBundle/Controller/ManageController.php
- src/AppBundle/Resources/views/Manage/availability.html.twig
We recently had an issue identifying what configuration environment we'd deployed to a server. This will make it easier to determine that in the future by displaying the environment clearly on the availability page.
Fixes [DDPB-2656](https://opgtransform.atlassian.net/browse/DDPB-2656)
I passed `$kernel->getEnvironment()` to the template and rendered it in the list.
- [N/A] The product team have tested these changes
> Expose the environment on the Frontend availability page

- src/AppBundle/Controller/Org/NoteController.php
- src/AppBundle/Resources/translations/client-notes.en.yml
- src/AppBundle/Resources/translations/client-profile.en.yml
- src/AppBundle/Resources/views/Org/ClientProfile/_notes.html.twig
- src/AppBundle/Resources/views/Org/ClientProfile/addNote.html.twig
- src/AppBundle/Resources/views/Org/ClientProfile/editNote.html.twig
Adds an informative notice to Note related sections/pages.
Addresses [DDPB-2581](https://opgtransform.atlassian.net/browse/DDPB-2581)
Simple re-use of existing macros.
Discovered that the `client` variable required by Twig was not set, despite Twig referencing it. This is a silent error on production, and displays an empty string where referenced. On dev, Twig displays a fatal error and therefore the issue was highlighted (notably, Behat tests did not pick this up as they run in prod mode).
I have set the required `$client` var for the template.
- [N/A] I have updated documentation (Confluence/GitHub wiki) where relevant
- …
> DDPB-2581: Adds notice to Notes section

- src/AppBundle/Resources/translations/admin-checklist.en.yml
- src/AppBundle/Resources/views/Admin/Client/Report/partials/_money-in-and-out.html.twig
- tests/behat/features/deputy/03-report/01-102/24-lodging-checklist.feature
To better allow case managers to complete the report checklist.
Fixes [DDPB-2568]
Adds a link just beyond all of the money in-out panels to allow user to quickly to return to the question for which the panel information relates.
Clicking this anchor link removes any previously entered data in behat only. Hence the test had to be moved to be after data was persisted. Browser behaves normally.
- [n/a] I have updated documentation (Confluence/GitHub wiki) where relevant
Checked with team. Fixed in DDPB-2648
Checked with team. Fixed in DDPB-2648
> Ddpb 2568 add checklist jump link

- src/AppBundle/Controller/BehatController.php
- tests/behat/bootstrap/DebugTrait.php
- tests/behat/bootstrap/LinksTrait.php
- tests/behat/bootstrap/UserTrait.php
The Behat controllers are used for debugging and test automation in non-production environments. However, due to a misconfiguration, they are currently available in production too.
Fixes [DDPB-2679](https://opgtransform.atlassian.net/browse/DDPB-2679)
The controller now properly throws an exception rather than returning it (the parent function was ignoring it).
I also removed functionality which was inspecting and resetting log files. Now that log messages are put to stderr (and therefore available in CloudWatch), this functionality isn't necessary (and doesn't work).
I considered trying to maintain the old behaviour by reading from stderr, but that's not possible in PHP. However, whilst the old behaviour is potentially convenient, I also think it's misleading and insecure.
> DDPB-2679: Hide Behat controller in production

- docker/confd/templates/behat.yml.tmpl
- tests/behat/features/admin/00-prechecks.feature
- tests/behat/features/admin/01-admin.feature
- tests/behat/features/admin/03-ad.feature
- tests/behat/features/admin/04-case-manager.feature
- tests/behat/features/deputy/01-registration-steps/00-prechecks.feature
- tests/behat/features/deputy/01-registration-steps/01-create-users.feature
- tests/behat/features/deputy/01-registration-steps/02-set-password.feature
- tests/behat/features/deputy/02-ndr/05-assets.feature
- tests/behat/features/deputy/02-ndr/10-submit.feature
- tests/behat/features/deputy/02-ndr/11-report-submission.feature
- tests/behat/features/deputy/03-report/01-102/22-submit-more-documents.feature
- tests/behat/features/deputy/03-report/01-102/23-report-resubmission.feature
- tests/behat/features/deputy/03-report/03-104/02-check-and-submit.feature
- tests/behat/features/deputy/03-report/03-104/03-lodging-checklist.feature
- tests/behat/features/deputy/04-user/03-userselfregister.feature
- tests/behat/features/deputy/04-user/06-codeputies.feature
- tests/behat/features/deputy/05-acl/02-pages-security.feature
- tests/behat/features/pa/01-registration-steps/00-prechecks.feature
- tests/behat/features/pa/01-registration-steps/01-admin-add-pa-users-and-activate.feature
- tests/behat/features/pa/03-report/02-common-report-sections.feature
- tests/behat/features/prof/01-registration-steps/00-prechecks.feature
- tests/behat/features/prof/01-registration-steps/01-admin-add-pa-users-and-activate.feature
- tests/behat/features/prof/03-report/02-common-report-sections.feature
- tests/behat/features/prof/03-report/07-submit-report.feature
- tests/behat/features/prof/03-report/08-lodging-checklist.feature
- tests/behat/features/prof/07-acl.feature
One restriction to running the automated test suites simulataneously is that some tests save and then reload the entire database state. These sweeping changes can interrupt and break other tests running on different threads.
This PR addresses some of the more trivial instances of this behaviour, minimising its impact.
Fixes [DDPB-2657](https://opgtransform.atlassian.net/browse/DDPB-2657)
After some extensive research on [DDPB-2623](https://opgtransform.atlassian.net/browse/DDPB-2623), several trivial instances were identified. In this PR, I removed this instances and did the small amount of cleanup necessary to keep the tests passing.
I also tidied up the `behat.yml` file, removing the unused "components" suite and removing the duplicate definition of the "admin" suite. …
> DDPB-2657: Remove trivial tests which save/load application state

- src/AppBundle/Resources/views/Layouts/moj_template.html.twig
In #1241, I inadvertently removed the application version number from the page footer. This change reinstates it.
I just copied across the code from before.
- N/A
- N/A
- N/A
- N/A
> DDPB-2646: Reinstate application version tag in footer

- src/AppBundle/Resources/views/Admin/Index/index.html.twig
- src/AppBundle/Resources/views/Components/Form/_input.html.twig
Upgrading to the GOV.UK Design System caused the filters admin index page to stack vertically, wasting space.
The issue was with incompatible GOV.UK Elements and GOV.UK Design System classes. I upgraded the CSS classes to all use the Design System.
As part of this I changed the `form_input` macro to use the `govuk-!-width-one-half` class only if no other width classes were provided in `inputClass`. Previously it was always added, which caused specificity issues.
> DDPB-2646: Fix alignment of form items on admin filters

- src/AppBundle/Controller/Admin/Client/ReportController.php
- src/AppBundle/Resources/translations/admin-checklist.en.yml
- src/AppBundle/Resources/views/Admin/Client/Report/Formatted/unsubmit_information.html.twig
- src/AppBundle/Resources/views/Admin/Client/Report/checklist.html.twig
- tests/behat/features/deputy/03-report/01-102/24-lodging-checklist.feature
When a report is unsubmitted, the case manager needs to know which sections were flagged for attention so that when re-visiting the checklist they dont have to go through the entire report again.
Fixes [DDPB-2569]
The prototype requested that the information be displayed in the table that displays any additional information added tto the checklist. Rather than displaying a single template, I have persisted an entry in the checklist information table. Since this meets the design criteria and will persist even if the report is re-submitted and then a further un-submission is actioned. Thus giving a more complete history of the report.
- [n/a] I have updated documentation (Confluence/GitHub wiki) where relevant
Lots of errors as a result of pulling in master. To be fixed elsewhere?
> Ddpb 2569 checklist unsubmitted sections

- src/AppBundle/Entity/Report/MoneyTransaction.php
- src/AppBundle/Resources/translations/report-money-transaction.en.yml
- tests/behat/features/prof/03-report/04-edit-report-sections.feature
Add extra copy to inform deputies not to include deputy costs in the money out section.
Fixes [DDPB-2658](https://opgtransform.atlassian.net/browse/DDPB-2658)
One liner to the translation file.
None.
- [N/A] I have updated documentation (Confluence/GitHub wiki) where relevant
- [N/A] There are no new frontend linting errors (`docker-compose run --rm npm run lint`)
> DDPB-2658: Adds 'Do not include deputy costs' note to Money Out section

- src/AppBundle/Resources/assets/scss/_shame.scss
- src/AppBundle/Resources/assets/scss/digideps/_details-banner.scss
- src/AppBundle/Resources/views/Org/ClientProfile/_detailsBanner.html.twig
Upgrades `.details-banner` CSS to new standards
Fixes [DDPB-2704](https://opgtransform.atlassian.net/browse/DDPB-2704)
Added a line to `_shame.scss` which makes `<strong>` and `<b>` tags render bold text as you'd expect (reversing a decision from GOV.UK Elements which will be phased out when that's deprecated).
Used flexbox for content alignment with a very simple float fallback for browsers which don't support it.
Deferred to #1259
> DDPB-2704: Upgrade `.details-banner` CSS to Design System standards

- src/AppBundle/Resources/assets/scss/digideps/_progress_indicator.scss
Upgrades `.progress-bar` CSS to new standards
Fixes [DDPB-2710](https://opgtransform.atlassian.net/browse/DDPB-2710)
Used BEM-style classes and simplified a lot of the dated CSS.
Made use of GOV.UK Design System mixins and variables to simplify definition.
Removed some old code referencing the CSS classes which wasn't being used.
Deferred to #1259
> DDPB-2710: Upgrade CSS for registration progress bar

- src/AppBundle/Resources/views/Org/ClientProfile/_detailsBanner.html.twig
Just ensures client is set before displaying the client's name
Fixes [DDPB-####](link to JIRA issue)
_Explain how your code addresses the purpose of the change_
_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about DigiDeps_
> DDPB-2433 fixed checks on client variable

- src/AppBundle/Resources/assets/javascripts/modules/detailsExpander.js
The `detailsExpander` module relies on the `form-group` class being used, but most pages now use the `govuk-from-group` class.
Fixes [DDPB-2731](https://opgtransform.atlassian.net/browse/DDPB-2731)
Either class may be used. 
In a perfect world we would use data attributes to identify the element but this is not simple due to them being created in templates.
> DDPB-2731: "More details" sections don't appear on PA fee and expense fields

- src/AppBundle/Resources/assets/scss/digideps/_alert.scss
- src/AppBundle/Resources/assets/scss/digideps/_icon.scss
- src/AppBundle/Resources/views/Macros/macros.html.twig
- src/AppBundle/Resources/views/Report/Balance/balance.html.twig
- src/AppBundle/Resources/views/Report/BankAccount/deleteConfirm.html.twig
- src/AppBundle/Resources/views/Report/Document/step2.html.twig
- src/AppBundle/Resources/views/Report/MoneyInShort/start.html.twig
- src/AppBundle/Resources/views/Report/MoneyOutShort/start.html.twig
Upgrade icon CSS to Design System standards
Fixes [DDPB-2706](https://opgtransform.atlassian.net/browse/DDPB-2706)
Simplified icon CSS and renamed to `.opg-icon` class (but left old class in place to support remaining icons)
Created an icon macro for easier reuse/management
Tided up alerts CSS
Used the notification macro in place of all remaining hand-coded alerts
Deferred to #1259
> DDPB-2706: Upgrade icon CSS to Design System standards

- tests/behat/features/pa/03-report/03-edit-report-sections.feature
The "PA deputy fees and expenses" section is only available to PA deputies. In Behat we explicitly test this section, whereas other sections are tested in professional and lay suites.
However, the Behat tests do not add any expenses. This means that not every part of the section is tested. As a result, a recent issue introduced by the PHP7 upgrade was not picked up by tests.
Fixes [DDPB-2743](https://opgtransform.atlassian.net/browse/DDPB-2743)
I updated the fees and expenses tests to add a new expense. I also updated the "money in" amount so that the accounts would balance and the report could be submitted.
- N/A
- N/A: only changes to tests
> DDPB-2743: Update Behat tests to add PA expenses

- src/AppBundle/Resources/views/Components/Form/_input.html.twig
Textarea inputs were only displaying at half size since updating to the new GOV UK styles. We needed them to be full-width to encourage more feedback from users.
Fixes [DDPB-2697](https://opgtransform.atlassian.net/browse/DDPB-2697?atlOrigin=eyJpIjoiNjI3ZWFhZWM2YzBjNGE0MWI2MjYzODM5MWRiYWQ4NjIiLCJwIjoiaiJ9)
I found out which macro was creating the inputs, then edited the set up to remove the half-width class
I used the [GOV UK design systems](https://design-system.service.gov.uk/components/textarea/) to see how they format the textarea example and followed their lead with 5 rows
> DDBP-2697 Remove half width class from textarea input macro

- src/AppBundle/Resources/views/Org/ClientProfile/_detailsBanner.html.twig
DDPB-2673 introduced a slight regression to the helpline box for lay deputies. This is because it is being given an additional CSS class which aligns and sizes it as for PA and Professional deputies. It's unlikely this would be noticed by any users, but in certain situations it pushes header down just a bit too far.
Fixes [DDPB-2750](https://opgtransform.atlassian.net/browse/DDPB-2750)
I only included the class for non-lay reports. I used the existing if statement, but used a temporary variable to stop us calling it three times.
-  N/A
> DDPB-2750: Only add details banner class for non-lay deputies

- package-lock.json
- src/AppBundle/Resources/assets/scss/digideps/_sections.scss
- src/AppBundle/Resources/translations/report-overview.en.yml
- src/AppBundle/Resources/views/Org/ClientProfile/_subsection.html.twig
- src/AppBundle/Resources/views/Report/Report/_subsection.html.twig
- src/AppBundle/Twig/ComponentsExtension.php
In the report overview, rejected sections should be clearly highlighted so that deputies can see what additional information is needed.
Fixes [DDPB-2769](https://opgtransform.atlassian.net/browse/DDPB-2769)
I fixed some bugs with applying the correct CSS class when a section is rejected. I also added the "Changes needed" label to all such sections for screenreaders and users with visual impairments.
I realised we have a variety of places where status translations are defined:
- common.en.yml (`notFinished` and `status.notFinished`)
- ndr-overview.en.yml (`status.notFinished` and `labels.incomplete`)
- report-overview.en.yml (`status.notFinished` and `labels.incomplete`)
It would probably be good to tidy that up at some point, so I'll add it to our tech debt list.
- Fixed with `npm audit …
> DDPB-2769: Restoring highlighting of rejected sections

- src/AppBundle/Controller/UserController.php
- src/AppBundle/Resources/translations/register.en.yml
The error message was attempting to display a link to the "sign in" and "reset your password" pages.
Fixes [DDPB-2752](https://opgtransform.atlassian.net/browse/DDPB-2752)
The simplest fix (and what I have implemented) is to remove the links, and just offer the text. 
It's not a simple case of adding the `raw` tag as the error text markup is constructed using the generic `_validation-summary.html.twig`, And applying `raw` to every error output is unsafe. Also, if a workaround was found to apply `raw` just in this scenario, the CSS styling of the link is inherited such that the link is red, so further work would be required to fix that.
The scenario for viewing this error in the first place is edge case as it is, and the text even without links seems sufficient enough to aid the user. …
> DDPB-2752: Fixes broken error message on registration page

- docs/PULL_REQUEST_TEMPLATE.md
- docs/TECH_DEBT.md
- docs/TESTING.md
We want to record known technical debt in DigiDeps.
I created a document to record tech debt (and [another in API](https://github.com/ministryofjustice/opg-digi-deps-api/pull/569)). I also added it as a documentation option in our PR template.
> Add technical debt document

- docs/TECH_DEBT.md
- src/AppBundle/Resources/assets/scss/_shame.scss
When introducing the GOV.UK Design System, we had to put in a fix for scaling issues caused by combining it with GOV.UK Elements. We did so by resetting the html and body font size to `initial`.
However, Internet Explorer does not support the `initial` keyword.
Fixes [DDPB-2775](https://opgtransform.atlassian.net/browse/DDPB-2775)
I instead used the value `100%`, which does the same thing and _is_ supported by Internet Explorer. It's just a bit less elegant.
I had to get a [Internet Explorer virtual machine](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) to verify the problem and the fix.
All N/A
> DDPD-2775: Fix font scaling in Internet Explorer

- Gulpfile.js
- package-lock.json
- package.json
- src/AppBundle/Resources/assets/javascripts/modules/show-hide-content.js
- src/AppBundle/Resources/assets/scss/_common.scss
- src/AppBundle/Resources/assets/scss/_shame.scss
- src/AppBundle/Resources/assets/scss/application-print.scss
- src/AppBundle/Resources/views/Layouts/application.html.twig
- src/AppBundle/Resources/views/Layouts/moj_template.html.twig
We are in the process of moving to the [GOV.UK Design System](https://design-system.service.gov.uk/). This involves removing our dependencies on `govuk-elements-sass`, `govuk_frontend_toolkit` and `govuk_template_mustache`.
In this PR we remove the dependency on `govuk_template_mustache`.
Fixes [DDPB-2789](https://opgtransform.atlassian.net/browse/DDPB-2789)
The core bit of work here is to remove `govuk_template_mustache` from our Gulp processes and its resultant CSS file from our HTML template. In doing so, we need to make a couple of replacements:
- Images and fonts are now pulled from `govuk-frontend` instead
- Some global overrides were added to `_shame.scss` because we still depend on them
- `show-hide-content.js` was extricated from `govuk_frontend_toolkit` into a separate …
> DDPB-2789: Deprecate GOV.UK Frontend Template

- tests/behat/bootstrap/ReportTrait.php
- tests/behat/features/deputy/03-report/01-102/09-any-other-info.feature
- tests/behat/features/deputy/03-report/01-102/17-money.feature
- tests/behat/features/deputy/03-report/02-103/00-start.feature
- tests/behat/features/deputy/03-report/02-103/01-money-103.feature
- tests/behat/features/deputy/03-report/02-103/02-check-and-submit.feature
- tests/behat/features/deputy/03-report/03-104/00-start.feature
- tests/behat/features/deputy/03-report/03-104/01-health-welfare.feature
- tests/behat/features/deputy/03-report/03-104/02-check-and-submit.feature
- tests/behat/features/deputy/03-report/03-104/03-lodging-checklist.feature
- tests/behat/features/deputy/07-infra-checks/00-documents.feature
- tests/behat/features/pa/03-report/01-report-edit-period.feature
- tests/behat/features/prof/03-report/01-report-edit-period.feature
We currently test 103 and 104 reports by fudging the data: we run through a 102 report, then change the account type to 103 and assign a new deputy. This ensures that the already-tested sections are filled out and allows us to specifically test the 103 sections and submit the report.
This causes a few issues: we're dynamically messing with data, causing race condition failures and not properly testing the functionality.
Fixes [DDPB-2797](https://opgtransform.atlassian.net/browse/DDPB-2797)
I removed the parts of the 103 and 104 tests which appropriated the 102 report, instead using the 103/104 fixtures. I then added scripts to fill in the minimum viable data for the sections which had already been tested.
I tidied up any references to 102 data which were still in the tests, and gave each …
> DDPB-2797: Complete 103 and 104 reports rather than fudging data

- client/src/AppBundle/Resources/views/Layouts/moj_template.html.twig
I originally did this as part of DDPB-2589, but overwrote it when merging from master 🙄
It's necessary for the skip link to work for keyboard users
> Reinstate "main-content" ID on <main>
